INSERT INTO ALUNO (NOME) VALUES
  ('Helena'),
  ('Alice'),
  ('Laura'),
  ('Manuela'),
  ('Valentina'),
  ('Sophia'),
  ('Isabella'),
  ('Heloísa'),
  ('Luiza'),
  ('Júlia'),
  ('Lorena'),
  ('Lívia'),
  ('Maria Luiza'),
  ('Cecília'),
  ('Eloá'),
  ('Giovanna'),
  ('Maria Clara'),
  ('Maria Eduarda'),
  ('Mariana'),
  ('Lara'),
  ('Beatriz'),
  ('Antonella'),
  ('Maria Júlia'),
  ('Emanuelly'),
  ('Isadora'),
  ('Ana Clara'),
  ('Melissa'),
  ('Ana Luiza'),
  ('Ana Júlia'),
  ('Esther');