INSERT INTO student (name)
VALUES  ('Karol'),
        ('Gabriel'),
        ('Jessica'),
        ('Stephanie'),
        ('Lucas'),
        ('Guilherme'),
        ('Julia'),
        ('Diego'),
        ('Iolanda'),
        ('Marco'),
        ('Raimundo'),
        ('Bruna'),
        ('Amanda'),
        ('Antonio'),
        ('Leonardo'),
        ('Gustavo'),
        ('Victor'),
        ('Marli'),
        ('Isabella'),
        ('Mayra'),
        ('Fernando'),
        ('Luca'),
        ('Renata'),
        ('Fabrico'),
        ('Paulo'),
        ('Durvalino'),
        ('BilL Gates'),
        ('Pharrel Willians'),
        ('Matue'),
        ('Lucas Carlos'),
        ('Duarte');
